on:
  push:
  pull_request:
    branches:
      - main

jobs:
  demo:
    runs-on: ubuntu-latest
    
    steps:
    - name: cloning the repo
      run: git clone https://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@github.com/sneha-dhande123/new-demo-repo.git
       
