on:
  push:
  pull_request:
    branches:
      - main

jobs:
  demo:
    runs-on: windows-latest
    
    steps:
    - name: cloning the new demo git
      uses: actions/checkout@v4
      with:
        repository: sneha-dhande123/new-demo-repo
        ref: main
        token: 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
        path: ${{github.workspace}}\postman
       
